server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    driver: postgres
    source: host=postgres.docker.localhost port=5432 user=postgres password=123456 dbname=vvgo-mall sslmode=disable
  redis:
    addr: redis:6379
    dial_timeout: 0.1s
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    addrs:
      - kafka:9092
  mongodb:
    uri: "mongodb://mongodb:27017"
    database: ""

trace:
  endpoint: http://jaeger.docker.localhost:14268/api/traces

auth:
  service_key: some-secret-key
  api_key: some-secret-key-for-forntend

casbin:
  enable: true
  debug: false
  model_path: rbac_model.conf
  auto_load: false
  auto_load_internal: 60
