server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=postgres.docker.localhost port=5432 user=postgres password=123456 dbname=vvgo-mall sslmode=disable
  redis:
    addr: redis.docker.localhost:6379
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:
  endpoint: http://jaeger.docker.localhost:14268/api/traces
