version: "3.7"

networks:
  app_net:
    external: true

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_ANONYMOUS_LOGIN=yes
    # volumes:
    # - ./zookeeper/conf/zoo.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
    # - ./data/zookeeper/data:/bitnami/zookeeper/data

  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      # - KAFKA_BROKER_ID=1
      # - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      # - JMX_PORT=9999
    # volumes:
    #   - ./data/kafka/data:/bitnami/kafka/data
    #   - ./data/kafka/config:/bitnami/kafka/config
    depends_on:
      - zookeeper

  # efak:
  #   build:
  #     context: ./efak
  #   container_name: efak
  #   ports:
  #     - 8048:8048
  #   networks:
  #     - app_net
  #   restart: always
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - ZK_HOSTS=zookeeper:2181
  #   volumes:
  #     - ./efak/conf/system-config.properties:/usr/local/efak/conf/system-config.properties
  #     - ./data/efak/logs:/usr/local/efak/logs
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   stdin_open: true
  #   tty: true

  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app_net
    restart: always
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      discovery.type: single-node
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      # - ./elasticsearch/cert/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      # - ./data/elk/elasticsearch/data:/usr/share/elasticsearch/data:z
      # - ./data/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins:z
      # - ./data/elk/elasticsearch/logs:/usr/share/elasticsearch/logs:z
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1

  kibana:
    # image: docker.elastic.co/kibana/kibana:8.0.0
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - KIBANA_SYSTEM_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    depends_on:
      - elasticsearch

  logstash:
    # image: docker.elastic.co/logstash/logstash:8.0.0
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: logstash
    ports:
      - 5044:5044
      # - "5000:5000/tcp"
      # - "5000:5000/udp"
      # - "9600:9600"
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
      - LOGSTASH_SYSTEM_PASSWORD=${LOGSTASH_SYSTEM_PASSWORD}
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      # - ./data/elk/logstash/data:/usr/share/logstash/data
    depends_on:
      - elasticsearch

  filebeat:
    # image: docker.elastic.co/beats/filebeat:8.0.0
    build:
      context: filebeat/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: filebeat
    user: root
    command:
      - -e
      - --strict.perms=false
    volumes:
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,Z
      # - ./data/elk/filebeat/data:/usr/share/filebeat/data
      # - ./data/elk/filebeat/log:/usr/share/filebeat/log
      - ./data/nginx/logs:/var/log/nginx
    depends_on:
      - logstash
      - elasticsearch
      - kibana

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/logs:/var/log/nginx
      # - /code:/var/www/html
