server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(mysql:3306)/vvgo-mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
  redis:
    addr: redis:6379
    dial_timeout: 0.1s
    read_timeout: 0.2s
    write_timeout: 0.2s

trace:
  endpoint: http://jaeger:14268/api/traces
