version: "3.7"

networks:
  app_net:
    external: true

services:
  # openresty:
  # image: openresty/openresty:alpine
  # container_name: openresty
  # ports:
  #   - 80:80
  #   - 443:443
  # networks:
  #   - app_net
  # restart: always
  # environment:
  #   - TZ=Asia/Shanghai
  # volumes:
  #   - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
  #   - ./openresty/conf.d:/etc/nginx/conf.d
  #   - ./openresty/lua:/etc/nginx/lua
  #   - ./data/openresty/logs:/usr/local/openresty/nginx/logs
  #   # - /code:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/logs:/var/log/nginx
      # - /code:/var/www/html
    depends_on:
      - vvgo-mall

  vvgo-mall:
    image: lyumikael/gomodd:v1.0.0
    container_name: vvgo-mall
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    networks:
      - app_net
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - GOPROXY=https://goproxy.cn,direct
    working_dir: /usr/local/go/src/github.com/lalifeier/vvgo-mall
    volumes:
      - ../..:/usr/local/go/src/github.com/lalifeier/vvgo-mall


  # account-service:
  #   image: kratos-blog/account-service:0.1.0
  #   container_name: account-service
  #   networks:
  #     - app_net
  #   restart: always
  #   privileged: true
  #   environment:
  #     - TZ=Asia/Shanghai
