version: "3.7"

networks:
  app_net:
    external: true

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/logs:/var/log/nginx
      # - /code:/var/www/html
    depends_on:
      - shop-admin

  shop-admin:
    # image: cosmtrek/air:latest
    build:
      context: ./air
    container_name: shop-admin
    working_dir: /go/src/github.com/vvgo-mall/app/shop/admin
    ports:
      - 8000:8000
    networks:
      - app_net
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - GOPROXY=https://goproxy.cn,direct
    volumes:
      - ../../:/go/src/github.com/vvgo-mall
    # depends_on:
    #   - account-service
    #   - auth-service

  # account-service:
  #   # image: cosmtrek/air:latest
  #   build:
  #     context: ./air
  #   container_name: account-service
  #   working_dir: /go/src/github.com/vvgo-mall/app/account/service
  #   ports:
  #     - 8001:8001
  #   networks:
  #     - app_net
  #   privileged: true
  #   restart: always
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - GOPROXY=https://goproxy.cn,direct
  #   volumes:
  #     - ../../:/go/src/github.com/vvgo-mall
  #   depends_on:
  #     - mysql
  #     - redis

  # auth-service:
  #   # image: cosmtrek/air:latest
  #   build:
  #     context: ./air
  #   container_name: auth-service
  #   working_dir: /go/src/github.com/vvgo-mall/app/auth/service
  #   ports:
  #     - 8002:8002
  #   networks:
  #     - app_net
  #   privileged: true
  #   restart: always
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - GOPROXY=https://goproxy.cn,direct
  #   volumes:
  #     - ../../:/go/src/github.com/vvgo-mall
  #   depends_on:
  #     - mysql
  #     - redis
