version: "3.7"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  # web-admin:
  #   image: vgo-web-admin:0.1.0
  #   ports:
  #     - 80:80

  # user-service:
  #   image: vgo-user-service:0.1.0
  #   restart: always
  #   hostname: user-service
  #   depends_on:
  #     - mysql
  #     - consul

  nginx:
    image: bitnami/nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /usr/local/docker/nginx/html:/usr/share/nginx/html
      - /usr/local/docker/nginx/logs:/var/log/nginx
      - /usr/local/docker/nginx/conf:/etc/nginx

  mysql:
    image: bitnami/mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - backend
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /usr/local/docker/mysql/conf:/etc/mysql/conf.d
      - /usr/local/docker/mysql/logs:/logs
      - /usr/local/docker/mysql/data:/var/lib/mysql
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend
    restart: always
    environment:
      TZ: Asia/Shanghai
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /usr/local/docker/redis/redis.conf:/etc/redis/redis.conf
      - /usr/local/docker/redis/data:/data

  consul:
    container_name: consul
    image: bitnami/consul:latest
    networks:
      - backend
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
    volumes:
      - /usr/local/docker/consul/data:/bitnami

  jaeger:
    container_name: jaegertracing
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411

  # prometheus:
  #   image: bitnami/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - backend
  #   restart: always
  #   environment:
  #     TZ: Asia/Shanghai
  #   volumes:
  #     - /usr/local/docker/prometheus/prometheus-persistence:/opt/bitnami/prometheus/data
  #     - /usr/local/docker/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
