name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.19.x]

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test
        run: make test

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
